# https://docs.netlify.com/configure-builds/file-based-configuration/
[build]
command = "pnpm build:apps && node packages/app-builder/preview-link-stg.js"
publish = "dist"
[[redirects]]
from = "/:appSlug/*"
to = "/:appSlug/index.html"
status = 200
[template.environment]
PUBLIC_SELF_HOSTED_SLUG = "Your organization slug"
